### ISSUE TITLE
Make the button uniform

### ISSUE THREAD

**Issue by sanzeeb3** [lijnam/wc_hbl_payment_gateway#10]
Let us make the button label "Set up" instead of "Manage" to make it uniform with other payments. I'd also propose to disable the payment gateway by default, which is also the case with other payment gateways.

![Annotation on 2021-06-26 at 19-30-54](https://user-images.githubusercontent.com/16817248/123514936-1aae7e80-d6b5-11eb-8d81-1c80a982be3c.png)

**Comment by lijnam** [comment]
@sanzeeb3 sure, Please create a PR.

**Comment by lijnam** [comment]
found out  that the button text changes to "Manage" if the payment gateway is enabled, if its disabled te button text is "Set up"

**Comment by lijnam** [comment]
but yeah, we should disable the payment gateway by default

**Comment by sanzeeb3** [comment]
Good catch @lijnam 👍
