### ISSUE TITLE
WPCS isn't a required package in production

### ISSUE THREAD

**Issue by sanzeeb3** [lijnam/wc_hbl_payment_gateway#24]
The plugin doesn't require wpcs to work.

https://github.com/lijnam/wc_hbl_payment_gateway/blob/44ac9042d57a937725b8d4c7c934c8cec7da5e79/composer.json#L12

The packages that are only required during development should be under `require-dev`

**Comment by lijnam** [comment]
fixed with https://github.com/lijnam/wc_hbl_payment_gateway/pull/25
