### ISSUE TITLE
PHP Notices and warnings after the redirection.

### ISSUE THREAD

**Issue by sanzeeb3** [lijnam/wc_hbl_payment_gateway#3]
I'm not sure what all the errors about. Noting here for reference.

> [25-Jun-2021 03:48:22 UTC] PHP Notice:  id was called <strong>incorrectly</strong>. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/estore/page.php'), get_template_part, locate_template, load_template, require('/themes/estore/template-parts/content-page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_pay, wc_get_template, include('/plugins/woocommerce/templates/checkout/order-receipt.php'), do_action('woocommerce_receipt_hbl_gateway'), WP_Hook->do_action, WP_Hook->apply_filters, WC_HBL_Gateway->send_request_to_bank, WC_HBL_Gateway->generate_hbl_bank_payment_form, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. ( in C:\laragon\www\dev\wp-includes\functions.php on line 5313
> [25-Jun-2021 03:48:22 UTC] PHP Notice:  id was called <strong>incorrectly</strong>. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/estore/page.php'), get_template_part, locate_template, load_template, require('/themes/estore/template-parts/content-page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_pay, wc_get_template, include('/plugins/woocommerce/templates/checkout/order-receipt.php'), do_action('woocommerce_receipt_hbl_gateway'), WP_Hook->do_action, WP_Hook->apply_filters, WC_HBL_Gateway->send_request_to_bank, WC_HBL_Gateway->generate_hbl_bank_payment_form, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. ( in C:\laragon\www\dev\wp-includes\functions.php on line 5313
> [25-Jun-2021 03:48:22 UTC] PHP Notice:  id was called <strong>incorrectly</strong>. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/estore/page.php'), get_template_part, locate_template, load_template, require('/themes/estore/template-parts/content-page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::order_pay, wc_get_template, include('/plugins/woocommerce/templates/checkout/order-receipt.php'), do_action('woocommerce_receipt_hbl_gateway'), WP_Hook->do_action, WP_Hook->apply_filters, WC_HBL_Gateway->send_request_to_bank, WC_HBL_Gateway->generate_hbl_bank_payment_form, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. ( in C:\laragon\www\dev\wp-includes\functions.php on line 5313
> [25-Jun-2021 03:48:22 UTC] PHP Notice:  Undefined property: WC_HBL_Gateway::$test_secret_key in C:\laragon\www\dev\wp-content\plugins\hbl-payment-for-woocommerce\includes\WC_HBL_Gateway.php on line 190
> [25-Jun-2021 03:48:22 UTC] PHP Notice:  Undefined property: WC_HBL_Gateway::$test_api_key in C:\laragon\www\dev\wp-content\plugins\hbl-payment-for-woocommerce\includes\WC_HBL_Gateway.php on line 191
> [25-Jun-2021 03:48:22 UTC] PHP Warning:  A non-numeric value encountered in C:\laragon\www\dev\wp-content\plugins\hbl-payment-for-woocommerce\includes\WC_HBL_Gateway.php on line 192

**Comment by lijnam** [comment]
i think it's about API keys
`[25-Jun-2021 03:48:22 UTC] PHP Notice: Undefined property: WC_HBL_Gateway::$test_secret_key in C:\laragon\www\dev\wp-content\plugins\hbl-payment-for-woocommerce\includes\WC_HBL_Gateway.php on line 190`
`[25-Jun-2021 03:48:22 UTC] PHP Notice: Undefined property: WC_HBL_Gateway::$test_api_key in C:\laragon\www\dev\wp-content\plugins\hbl-payment-for-woocommerce\includes\WC_HBL_Gateway.php on line 191`

**Comment by lijnam** [comment]
fixed  on https://github.com/lijnam/wc_hbl_payment_gateway/pull/7
